Initial deb and rpm packaging (#1278)
* Initial deb and rpm packaging

- Uses https://github.com/jordansissel/fpm
- Builds simple deb and rpm packages that installs the otelcol
binary to `/usr/bin/otelcol` and `examples/otel-local-config.yaml`
to `/etc/otel-collector/config.yaml`.
- TODO: create systemd service scripts

* Packaging updates

- Add support for arm64 packages
- Move files to internal/buildscripts/packaging/
- Use single Dockerfile for local deb and rpm builds
- Explicitly set output dir for packages in circleci

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -121,6 +121,8 @@ workflows:
             - coverage
             - windows-test
             - windows-msi
+            - deb-package
+            - rpm-package
           filters:
             branches:
               ignore: /.*/
@@ -141,6 +143,22 @@ workflows:
             tags:
               ignore: /.*/
       - check-links:
+          filters:
+            tags:
+              only: /^v([0-9])+.([0-9])+.([0-9])+.*/
+      - build-package:
+          name: deb-package
+          package_type: deb
+          requires:
+            - cross-compile
+          filters:
+            tags:
+              only: /^v([0-9])+.([0-9])+.([0-9])+.*/
+      - build-package:
+          name: rpm-package
+          package_type: rpm
+          requires:
+            - cross-compile
           filters:
             tags:
               only: /^v([0-9])+.([0-9])+.([0-9])+.*/
@@ -314,6 +332,41 @@ jobs:
       - run:
           name: Validate MSI
           command: .\internal\buildscripts\packaging\msi\make.ps1 Confirm-MSI
+      - persist_to_workspace:
+          root: ~/
+          paths: project/bin
+
+  build-package:
+    executor: golang
+    parameters:
+      package_type:
+        type: enum
+        enum: ["deb", "rpm"]
+    steps:
+      - checkout
+      - attach_to_workspace
+      - run:
+          name: Install fpm and dependencies
+          command: |
+            sudo apt-get update
+            sudo apt-get install -y ruby ruby-dev rubygems build-essential rpm
+            sudo gem install --no-document fpm -v 1.11.0
+      - run:
+          name: Build << parameters.package_type >> amd64 package
+          command: ./internal/buildscripts/packaging/fpm/<< parameters.package_type >>/build.sh "${CIRCLE_TAG:-}" "amd64" "./bin/"
+      - run:
+          name: Build << parameters.package_type >> arm64 package
+          command: ./internal/buildscripts/packaging/fpm/<< parameters.package_type >>/build.sh "${CIRCLE_TAG:-}" "arm64" "./bin/"
+      - run:
+          name: Test << parameters.package_type >> package installation
+          command: |
+            if [[ "<< parameters.package_type >>" = "deb" ]]; then
+                sudo dpkg -i bin/otel-collector*amd64.deb
+            else
+                sudo rpm -ivh bin/otel-collector*x86_64.rpm
+            fi
+            test -f /usr/bin/otelcol || (echo "/usr/bin/otelcol not found!" && exit 1)
+            test -f /etc/otel-collector/config.yaml || (echo "/etc/otel-collector/config.yaml not found" && exit 1)
       - persist_to_workspace:
           root: ~/
           paths: project/bin
