Update prepare-release.yml
Validate version format in release workflow

diff --git a/.github/workflows/prepare-release.yml b/.github/workflows/prepare-release.yml
--- a/.github/workflows/prepare-release.yml
+++ b/.github/workflows/prepare-release.yml
@@ -26,6 +26,34 @@ jobs:
       - uses: actions/checkout@v3
         with:
           fetch-depth: 0
+      - name: Validate version format
+        run: |
+          # Define the regular expression pattern for the version format.
+          version_pattern='^[0-9]+\.[0-9]+\.[0-9]+(-rc[0-9]+)?$'
+          
+          # Check if candidate-stable matches the version pattern.
+          if ! [[ "${{ inputs.candidate-stable }}" =~ $version_pattern ]]; then
+            echo "Invalid candidate-stable version format! Expected format: x.y.z or x.y.z-rcn"
+            exit 1
+          fi
+          
+          # Check if current-stable matches the version pattern.
+          if ! [[ "${{ inputs.current-stable }}" =~ $version_pattern ]]; then
+            echo "Invalid current-stable version format! Expected format: x.y.z or x.y.z-rcn"
+            exit 1
+          fi
+          
+          # Check if candidate-beta matches the version pattern.
+          if ! [[ "${{ inputs.candidate-beta }}" =~ $version_pattern ]]; then
+            echo "Invalid candidate-beta version format! Expected format: x.y.z or x.y.z-rcn"
+            exit 1
+          fi
+          
+          # Check if current-beta matches the version pattern.
+          if ! [[ "${{ inputs.current-beta }}" =~ $version_pattern ]]; then
+            echo "Invalid current-beta version format! Expected format: x.y.z or x.y.z-rcn"
+            exit 1
+          fi    
       # Make sure that there are no open issues with release:blocker label in Core. The release has to be delayed until they are resolved.
       - name: Check blockers in core
         env:
